const mongoose = require("mongoose");

const loanApplicationSchema = new mongoose.Schema(
  {
    id: { type: String, unique: true, required: true, index: true },
    borrowerName: { type: String, required: true, trim: true },
    pan: {
      type: String,
      required: true,
      uppercase: true,
      match: /^[A-Z]{5}[0-9]{4}[A-Z]$/,
    },
    mobile: { type: String, required: true, match: /^[6-9]\d{9}$/ },
    amount: { type: Number, required: true, min: 5000 },
    purpose: {
      type: String,
      required: true,
      lowercase: true,
      enum: [
        "personal",
        "consumer",
        "education",
        "medical",
        "emergency",
        "sme",
        "working_capital",
        "shopping",
        "electronics",
        "travel",
        "healthcare",
        "home_improvement",
        "other",
      ],
    },
    tenure: { type: Number, required: true },
    cibilScore: { type: Number, required: true, min: 300, max: 900 },
    monthlyIncome: { type: Number, required: true },
    dlaId: { type: String, default: "DLA-CONSUMER", index: true },
    userId: { type: String, default: null, index: true },
    creditAccountId: { type: String, ref: "CreditAccount", default: null, index: true },
    loanIntentId: { type: String, default: null },
    offerId: { type: String, default: null },
    lenderId: { type: String, default: null, index: true },
    lenderProductId: { type: String, default: null },
    interestRate: { type: Number, default: 14.5 },
    APR: { type: Number, default: 15.0 },
    emi: { type: Number, default: 0 },
    processingFee: { type: Number, default: 0 },
    totalRepayment: { type: Number, default: 0 },
    disbursedAmount: { type: Number, default: 0 },
    outstandingPrincipal: { type: Number, default: 0 },
    totalPaid: { type: Number, default: 0 },
    installmentsCount: { type: Number, default: 0 },
    installmentsPaid: { type: Number, default: 0 },
    nextDueDate: { type: Date, default: null },
    idempotencyKey: { type: String, default: null, index: true },
    disbursedAt: { type: Date, default: null },
    closedAt: { type: Date, default: null },
    status: {
      type: String,
      index: true,
      enum: [
        "DRAFT",
        "SUBMITTED",
        "ELIGIBILITY_CHECK",
        "OFFERS_AVAILABLE",
        "OFFER_SELECTED",
        "KFS_GENERATED",
        "KFS_ACCEPTED",
        "ROUTED",
        "LENDER_REVIEW",
        "APPROVED",
        "DISBURSAL_PENDING",
        "DISBURSED",
        "ACTIVE",
        "PARTIALLY_REPAID",
        "FULLY_REPAID",
        "CLOSED",
        "OVERDUE",
        "DEFAULTED",
        "REJECTED",
        "EXPIRED",
        "CANCELLED",
        "WITHDRAWN",
        // Legacy backward compatibility
        "new",
        "pending_review",
        "routed",
        "disbursed",
        "rejected",
      ],
      default: "SUBMITTED",
    },
    routedTo: { type: String, ref: "LenderProduct", default: null, index: true },
    routedAt: { type: Date, default: null },
    kfsGenerated: { type: Boolean, default: false },
    kfsPresentedAt: { type: Date, default: null },
    kfsAcceptedAt: { type: Date, default: null },
    rejectionReasonCode: {
      type: String,
      enum: [
        "INSUFFICIENT_INCOME",
        "CREDIT_CRITERIA_NOT_MET",
        "HIGH_OBLIGATIONS",
        "DOCUMENTATION_ISSUE",
        "PRODUCT_UNAVAILABLE",
        "OTHER",
        null,
      ],
      default: null,
    },
    rejectionReasonText: { type: String, default: "" },
    declineExplanation: { type: String, default: "" },
    aaConsent: { type: Boolean, default: true },
  },
  { timestamps: true }
);

loanApplicationSchema.set("toJSON", { virtuals: false });
loanApplicationSchema.set("toObject", { virtuals: false });

module.exports = mongoose.model("LoanApplication", loanApplicationSchema);
